### ISSUE TITLE
Scenes ripple effect is not noticeable enough

### ISSUE THREAD

**Issue by guyluz11** [CyBear-Jinni/CBJ_App#204] opened 2021-06-15 14:43 UTC
Make pressing ripple more noticeable, maybe white ripple.

![image](https://user-images.githubusercontent.com/9304740/122073029-c4158a80-ce00-11eb-83f2-277184076c90.png)

**Comment by samordoch** [comment] 2021-06-15 15:09
I'll take it

**Comment by chena-1** [comment] 2021-07-17 10:55
Duplicate of #208 solved

**Closed** 2021-07-17 10:56 UTC
