### ISSUE TITLE
Devices screen is not responsive

### ISSUE THREAD

**Issue by Tamir198** [CyBear-Jinni/cbj_app#342] opened 2021-11-12 11:38 UTC
Hey, I have looked at this screen:

![image](https://user-images.githubusercontent.com/34707669/141461246-5c2cc015-8e4b-4d76-b22e-fc63b4a4f222.png)

Looks like its not responsive and it would be nice if you can fix this.

**Comment by Brolan14** [comment] 2021-11-13 07:31
i think i can help you with your problem,but first can you tell me what should be fix , your device frozen or this program is not responsive

**Comment by Tamir198** [comment] 2021-11-13 10:43
@Brolan14   The program is not responsive

**Comment by guyluz11** [comment] 2021-11-13 10:54
I think @Tamir198  is talking about the

> bottom overflowed by 9.7 pixels

**Comment by Atharv-Joshi** [comment] 2021-11-22 15:05
I would like to work on this if its still pending?

**Comment by guyluz11** [comment] 2021-11-22 17:52
Sure @Atharv-Joshi

**Comment by Atharv-Joshi** [comment] 2021-12-01 11:31
Hey! I am currently busy so I dont think I can do a pr right now.
So you can unassign me , the issue will be good opportunity for a begineer and I dont want to block it1

**Comment by guyluz11** [comment] 2022-10-03 21:20
I have just added to the Wiki instructions on [how to get to the demo mode](https://github.com/CyBear-Jinni/cbj_app/wiki/How-to-open-app-in-demo-mode) so use it to test that.

**Comment by AdityaKeshan** [comment] 2022-10-04 13:19
Hi, I would like to work on this

**Comment by AdityaKeshan** [comment] 2022-10-04 18:21
![image](https://user-images.githubusercontent.com/60391695/193895652-a5c779d4-85ae-4fef-b093-28af97650e08.png)
Hi, The page seems to be working fine. There was no overflow or misalignment problem.

**Comment by guyluz11** [comment] 2022-10-04 18:26
Did you try on several screen sizes?
I do remember that I have tried to fix that but not what happened in the end.

I think in the picture he is using a google pixel 4 screen size

**Comment by AdityaKeshan** [comment] 2022-10-04 18:26
yeah i tried using emulator. Works fine

**Comment by guyluz11** [comment] 2022-10-04 18:38
Cool we are all good :).

Would you like to get a new issue?

> yeah i tried using emulator. Works fine

**Comment by guyluz11** [comment] 2022-10-04 18:46
@AdityaKeshan 
Here you go
https://github.com/CyBear-Jinni/cbj_app/issues/487

Please comment there so that I can assign it to you

**Comment by guyluz11** [comment] 2022-10-04 18:47
@Tamir198 if you keep getting that please reopen the issue.

Will close it now as @AdityaKeshan can't reproduce.

**Closed by guyluz11** 2022-10-04 18:47 UTC
Labels: bug, good first issue, hacktoberfest
